name: Bug report
description: Create a report to help BumbleVue improve.
title: Issue Title
labels:
  - 'Status: Needs Triage'
body:
  - type: markdown
    attributes:
      value: >
        ## Overview


        BumbleVue is a free community-driven project that is maintained by volunteers rather than a paid, dedicated team.
          By following the bug report template, you can help us identify and resolve issues more efficiently.
          This will allow us to focus on the most critical problems and improve the overall quality of BumbleVue.

        ## Issue Creation Guidelines


        To help us assist you better, please follow these mandatory requirements when creating an issue:


        ### Reproducer


        Provide a clear and concise executable example that reproduces the issue.


        ### Provide a Pull Request

        We highly encourage contributions from the community! If you have the time and ability, consider submitting a pull request to address this issue. Here's how you can get started:

          1. Fork the repository.
          2. Create a new branch (`git checkout -b feature/YourFeatureName`).
          3. Run "npm run dev" command to deploy the showcase locally using the monorepo.
          4. Make your changes.
          5. Commit your changes (`git commit -m 'Add some feature'`).
          6. Push to the branch (`git push origin feature/YourFeatureName`).
          7. Open a pull request.


        ### Discussions and Questions


        Please refrain from creating issue tickets for questions or support requests. Instead, use the GitHub Discussions for assistance.


        ## New Issue Report
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the report is about.
    validations:
      required: true
  - type: input
    id: pull_request
    attributes:
      label: Pull Request Link
      description: Link to your pull request.
    validations:
      required: false
  - type: checkboxes
    id: reason_for_no_pr
    attributes:
      label: Reason for not contributing a PR
      options:
        - label: Lack of time
        - label: Unsure how to implement the fix/feature
        - label: Difficulty understanding the codebase
        - label: Other
    validations:
      required: false
  - type: textarea
    id: pr_other
    attributes:
      label: Other Reason
      description: >-
        If your answer to the previous question is "Other", please explain the
        reason.
    validations:
      required: false
  - type: input
    id: reproducer
    attributes:
      label: Reproducer
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment.
    validations:
      required: true
  - type: input
    id: pr-version
    attributes:
      label: Vue version
      placeholder: x.x.x
    validations:
      required: true
  - type: input
    id: bumblevue-version
    attributes:
      label: BumbleVue version
      placeholder: 4.x.x
      description: >-
        Only issues related to v4 are valid.
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node version
      placeholder: x.x.x
    validations:
      required: false
  - type: input
    id: browsers
    attributes:
      label: Browser(s)
      description: >-
        List specific browser(s) the problem occurs on or leave blank if ALL
        browsers
      placeholder: |
        e.g. Safari 15, iOS 15.4, Chrome 90
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise description of how to make the issue happen.
      placeholder: |
        1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
