contact_links:
    - name: Feature request
      url: https://github.com/CJDevStudios/bumblevue/discussions/categories/feature-suggestions
      about: Propose an enhancement at discussions.
    - name: Support
      url: https://github.com/CJDevStudios/bumblevue/discussions
      about: Community support can be found at discussions.
